version: "3.2"

include:
  - docker-compose.yml

services:
  bun:
    build: ./docker/bun
    image: example_tasks_bun
    cap_drop: [all]
    working_dir: /var/www/src
    entrypoint: bun
    command: install --concurrent-scripts 8 -y -p --no-cache --frozen-lockfile --no-save
    volumes: [./tasks_fe/:/var/www]
  bun_tests:
    build: ./docker/bun
    image: example_tasks_bun
    cap_drop: [all]
    working_dir: /var/www/tests
    entrypoint: bun
    command: install --concurrent-scripts 8 -y -p --ignore-scripts --no-cache --frozen-lockfile --no-save
    volumes: [./tasks_fe/:/var/www]
  npm:
    build: ./docker/npm
    image: example_tasks_npm
    cap_drop: [all]
    working_dir: /var/www/src
    entrypoint: npm
    command: ci --loglevel http --omit=optional
    volumes: [./tasks_fe/:/var/www]
  npm_tests:
    build: ./docker/npm
    image: example_tasks_npm
    cap_drop: [all]
    working_dir: /var/www/tests
    entrypoint: npm
    command: ci --ignore-scripts --loglevel notice
    volumes: [./tasks_fe/:/var/www]
  biome:
    build: ./docker/bun
    image: example_tasks_bun
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: bun run tests/node_modules/.bin/biome check .
    volumes: [./tasks_fe:/var/www:ro]
    network_mode: none
  stylelint:
    build: ./docker/bun
    image: example_tasks_bun
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: bun run tests/node_modules/.bin/stylelint 'src/**/*.css' --config-basedir ./tests
    volumes: [./tasks_fe:/var/www:ro]
    network_mode: none
  tsclint:
    build: ./docker/bun
    image: example_tasks_bun
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: bun run tests/node_modules/.bin/tsc
    volumes: [./tasks_fe:/var/www:ro]
    network_mode: none
  htmlvalidate:
    build: ./docker/bun
    image: example_tasks_bun
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: bun run tests/node_modules/.bin/html-validate ./src/
    volumes: [./tasks_fe:/var/www:ro]
    network_mode: none
  esbuild:
    build: ./docker/bun
    image: example_tasks_bun
    cap_drop: [all]
    working_dir: /var/www
    entrypoint: sh -c "
      rm -rf dist/* \
      && bun run tests/node_modules/.bin/esbuild --bundle src/*.js src/*.css src/images/*.* --loader:.jpg=copy --analyze \
        --platform=browser --target=es2020 --minify --legal-comments=none --format=esm --outdir=dist/ \
        --define:globalThis.PROD=true \
      && bun run tests/node_modules/.bin/html-minifier-terser --collapse-whitespace --preserve-line-breaks --remove-comments \
        --input-dir ./src/ --output-dir ./dist/ --file-ext html \
      && ./dist_hash.sh \
      && gzip -k -f -9 dist/*.js dist/*.css dist/*.html \
      && stat -c '%n %s' src/*.html dist/*.gz dist/images/*"
    volumes: [./tasks_fe:/var/www]
    network_mode: none
  vitest:
    build: ./docker/npm
    image: example_tasks_npm
    cap_drop: [all]
    working_dir: /var/www/tests
    entrypoint: timeout -s kill 20 node_modules/.bin/vitest run
    volumes: [./tasks_fe/:/var/www]
    network_mode: none
